version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development 
    volumes:
      - ./:/app
      - node-mod:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=gaurav
      - MONGO_PASSWORD=root
      - SESSION_SECRET=anything
    command: ["npm", "run", "dev"]
  mongo:
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gaurav
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  node-mod: